_target_: lightning.pytorch.trainer.Trainer

default_root_dir: "/Using/esmdiff/output"

min_epochs: 10000 # prevents early stopping
max_epochs: 10000

accelerator: cpu
devices: 1

# mixed precision for extra speed-up
precision: bf16-true

# perform a validation loop every N training epochs
check_val_every_n_epoch: 1

# set True to to ensure deterministic results
# makes training slower but gives more reproducibility than just setting seeds
deterministic: False

# gradient_clip_val: 0.5